from gen.messages_pb2 import Molecule
from nodes.parse import parse
from gen.axiom_context import SecretStatus


class _TestContext:
    """Minimal AxiomContext implementation for unit tests."""

    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def __init__(self, m: dict, revoked: set) -> None:
            self._m = m or {}
            self._revoked = revoked or set()
        def get(self, name: str):
            v = self._m.get(name)
            return (v, True) if v is not None else ("", False)
        def status(self, name: str) -> SecretStatus:
            if name in self._m:
                return SecretStatus.AVAILABLE
            if name in self._revoked:
                return SecretStatus.REVOKED
            return SecretStatus.UNSET

    def __init__(self, secrets_map: dict | None = None, revoked_names: set | None = None) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets(secrets_map or {}, revoked_names)
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


# Independent oracle: PubChem CID 2244 (aspirin), fetched live from
# https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244/property/... —
# MolecularFormula=C9H8O4, MolecularWeight=180.16, HeavyAtomCount=13. These
# are computed by NCBI's own toolkit (Cactvs), independent of RDKit.
def test_parse_aspirin_matches_pubchem():
    ax = _TestContext()
    result = parse(ax, Molecule(smiles="CC(=O)Oc1ccccc1C(=O)O"))
    assert result.valid is True
    assert result.error == ""
    assert result.canonical_smiles == "CC(=O)Oc1ccccc1C(=O)O"
    assert result.formula == "C9H8O4"
    assert abs(result.molecular_weight - 180.16) < 0.01
    assert result.num_atoms == 13
    assert result.num_bonds == 13
    assert result.num_rings == 1


# Independent oracle: benzene is C6H6, MW 78.11 g/mol — a basic chemistry
# fact, not an RDKit-specific computation. The molblock below is a
# hand-authored MDL V2000 molfile (standard alternating-bond hexagon), not
# generated by this package's own code, so parsing it correctly exercises
# the molblock input path against ground truth we didn't produce ourselves.
_BENZENE_MOLBLOCK = """
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
M  END
"""


def test_parse_molblock_benzene():
    ax = _TestContext()
    result = parse(ax, Molecule(molblock=_BENZENE_MOLBLOCK))
    assert result.valid is True
    assert result.canonical_smiles == "c1ccccc1"
    assert result.formula == "C6H6"
    assert abs(result.molecular_weight - 78.11) < 0.01
    assert result.num_atoms == 6
    assert result.num_bonds == 6
    assert result.num_rings == 1


def test_parse_smiles_takes_precedence_over_molblock():
    # When both are set, smiles wins (documented input precedence).
    ax = _TestContext()
    result = parse(ax, Molecule(smiles="CCO", molblock=_BENZENE_MOLBLOCK))
    assert result.valid is True
    assert result.canonical_smiles == "CCO"


def test_parse_invalid_smiles_returns_structured_error():
    ax = _TestContext()
    result = parse(ax, Molecule(smiles="not_a_valid_smiles((("))
    assert result.valid is False
    assert result.error != ""
    assert result.canonical_smiles == ""


def test_parse_empty_input_returns_structured_error():
    ax = _TestContext()
    result = parse(ax, Molecule())
    assert result.valid is False
    assert result.error != ""


def test_parse_is_deterministic():
    ax = _TestContext()
    r1 = parse(ax, Molecule(smiles="CC(=O)Oc1ccccc1C(=O)O"))
    r2 = parse(ax, Molecule(smiles="CC(=O)Oc1ccccc1C(=O)O"))
    assert r1.canonical_smiles == r2.canonical_smiles
    assert r1.molecular_weight == r2.molecular_weight
